### PR TITLE
Resource generator --use-model #297 fixes #328

### LINKED ISSUE #328: Integration test to resources fails, when basic implementation contains a model.
If the resource generator does more than just a empty basic implementation (see #297) the tests fails: 

See [here](https://travis-ci.org/gobuffalo/buffalo/jobs/214762148#L1481)

```
Step 32 : RUN buffalo g resource admins --skip-model
 ---> Running in 8ccf04b9e3eb
Buffalo version 0.8.0.dev
--> actions/admins.go
--> actions/admins_test.go
--> gofmt -w .
 ---> 1428b9ae935b
Removing intermediate container 8ccf04b9e3eb
Step 33 : RUN filetest -c $GOPATH/src/github.com/gobuffalo/buffalo/buffalo/cmd/filetests/resource_skip_model.json
 ---> Running in eea7a90220e3
All of your tests have passed with flying colors!
 ---> 76a1858463d8
Removing intermediate container eea7a90220e3
Step 34 : RUN rm actions/admins_test.go
 ---> Running in eb9f33fdb703
 ---> ec66716a3e22
Removing intermediate container eb9f33fdb703
Step 35 : RUN buffalo test -race
 ---> Running in 7c68a1d8022e
Buffalo version 0.8.0.dev
dropped database /go<no value>/hello_world_test.sqlite
created database /go<no value>/hello_world_test.sqlite
dumped schema for /go<no value>/hello_world_development.sqlite
loaded schema for /go<no value>/hello_world_test.sqlite
go test -p 1 -race hello_world hello_world/actions hello_world/grifts hello_world/models
# hello_world/actions
actions/admins.go:23: undefined: models in models.Admins
actions/admins.go:44: undefined: models in models.Admin
actions/admins.go:59: undefined: models in models.Admin
actions/admins.go:67: undefined: models in models.Admin
actions/admins.go:101: undefined: models in models.Admin
actions/admins.go:117: undefined: models in models.Admin
actions/admins.go:152: undefined: models in models.Admin
actions/users.go:23: undefined: models in models.Users
actions/users.go:44: undefined: models in models.User
actions/users.go:59: undefined: models
actions/users.go:59: too many errors
```

If the generator generates the basic functions for adding, editing and removing entries, there is a reference to the models package inside the generated code. If the generator runs with the flag `--skip-model` the code can cause compiler errors, because of a missing model definition.

### PR DESCRIPTION
**Pull request by as27**
Generates a basic implementation for a resource, which supports crud functionality for a existing model.

### CODE REVIEW

**Comment by markbates** [comment]
I ran `buffalo g resource user name email bio:text`

it's output:

```
Buffalo version 0.8.0

--> actions/user.go
--> actions/user_test.go
--> buffalo db g model user name email bio:text
v3.13.3

--> models/user.go
--> models/user_test.go
--> goimports -w .
> migrations/20170327183424_create_users.up.fizz
> migrations/20170327183424_create_users.down.fizz
--> goimports -w .
```

The `UserResource`, however, didn't have any of the model stuff in it. It should.

```go
package actions

import "github.com/gobuffalo/buffalo"

type UserResource struct {
	buffalo.Resource
}

// List default implementation.
func (v UserResource) List(c buffalo.Context) error {
	return c.Render(200, r.String("User#List"))
}

// Show default implementation.
func (v UserResource) Show(c buffalo.Context) error {
	return c.Render(200, r.String("User#Show"))
}

// New default implementation.
func (v UserResource) New(c buffalo.Context) error {
	return c.Render(200, r.String("User#New"))
}

// Create default implementation.
func (v UserResource) Create(c buffalo.Context) error {
	return c.Render(200, r.String("User#Create"))
}

// Edit default implementation.
func (v UserResource) Edit(c buffalo.Context) error {
	return c.Render(200, r.String("User#Edit"))
}

// Update default implementation.
func (v UserResource) Update(c buffalo.Context) error {
	return c.Render(200, r.String("User#Update"))
}

// Destroy default implementation.
func (v UserResource) Destroy(c buffalo.Context) error {
	return c.Render(200, r.String("User#Destroy"))
}
```

File: generators/resource/templates/actions/resource-use_model.go.tmpl [hunk 1]
```diff
@@ -0,0 +1,166 @@
...
+type {{.camel}}Resource struct{
+	buffalo.Resource
+}
+
+// List gets all {{.camel}}. This function is mapped to the the path 
+// GET /{{.under}} 
+func (v {{.camel}}Resource) List(c buffalo.Context) error {
+	// Get the DB connection from the context
+	tx := c.Value("tx").(*pop.Connection)
+	{{.downFirstCap}} := &models.{{.camel}}{}
```
Comment (markbates) [inline generators/resource/templates/actions/resource-use_model.go.tmpl]: This should be plural.

It's generating `user := &models.User{}`, but it should be `users := &models.Users{}`

**Comment by markbates** [comment]
This should generate all of the `*.html` files as well. Each file can contain something basic like:

```html
<h1>Users#List</h1>
Find me at templates/users/list.html
```

File: generators/resource/templates/actions/resource-use_model.go.tmpl (hunk 1 above)
Comment (as27) [inline generators/resource/templates/actions/resource-use_model.go.tmpl]: I thought that resources are always generated with plural args: 'buffalo g resource users name email bio:text' then the logic works. But I am going to change that.

Comment (as27) [inline generators/resource/templates/actions/resource-use_model.go.tmpl]: The model stuff is just implemented with the `--use-model` flag. Because otherwise the tests will fail.

Comment (markbates) [inline generators/resource/templates/actions/resource-use_model.go.tmpl]: Then the tests need to be fixed. The `--use-model` flag should be used if you have an existing model, but the default, without any flags, should generate everything.

It's ok in the Dockerfile to delete stuff that was previously generated in the tests, or to create a new app, etc...

**Comment by as27** [comment]
* Logic of the flags changed
* added a basic structure for html templates. Later just the files can hold more logic
* changed the generator also to deal with a singular definition.

File: generators/resource/templates/actions/resource-use_model.go.tmpl [hunk 2]
```diff
@@ -0,0 +1,172 @@
...
+		// Make the errors available inside the html template
+		c.Set("errors", verrs.Errors)
+		// Render again the new.html template that the user can
+		// correct the input.
+		return c.Render(422, r.HTML("{{.underPlural}}/new.html"))
+	}
+	// If there are no errors set a success message
+	c.Flash().Add("success", "{{.model}} was created successfully")
+	// and redirect to the {{.underPlural}} index page
+	return c.Redirect(301, "/{{.underPlural}}")
```
Comment (markbates) [inline generators/resource/templates/actions/resource-use_model.go.tmpl]: Have this redirect to the `Show` action. `/users/1234`

File: generators/resource/templates/actions/resource-use_model.go.tmpl [hunk 3]
```diff
@@ -0,0 +1,172 @@
...
+		// Make the errors available inside the html template
+		c.Set("errors", verrs.Errors)
+		// Render again the edit.html template that the user can
+		// correct the input.
+		return c.Render(422, r.HTML("{{.underPlural}}/edit.html"))
+	}
+	// If there are no errors set a success message
+	c.Flash().Add("success", "{{.model}} was edited successfully")
+	// and redirect to the {{.underPlural}} index page
+	return c.Redirect(301, "/{{.underPlural}}")
```
Comment (markbates) [inline generators/resource/templates/actions/resource-use_model.go.tmpl]: Have this redirect to the `Show` action. `/users/1234`

File: generators/resource/templates/actions/resource-use_model.go.tmpl [hunk 4]
```diff
@@ -0,0 +1,172 @@
...
+	// To find the {{.model}} the parameter {{.singular}}_id is used. 
+	err := tx.Find({{.varSingular}}, c.Param("{{.singular}}_id"))
+	if err != nil {
+		return err
+	}
+	err = tx.Destroy({{.varSingular}})
+	if err != nil {
+		return err
+	}
+	// Redirect to the {{.underPlural}} index page
```
Comment (markbates) [inline generators/resource/templates/actions/resource-use_model.go.tmpl]: Add a flash message here to say that it was deleted.

File: generators/resource/templates/actions/resource-use_model.go.tmpl (hunk 2 above)
Comment (markbates) [inline generators/resource/templates/actions/resource-use_model.go.tmpl]: I think this should be a `302`.

File: generators/resource/templates/actions/resource-use_model.go.tmpl (hunk 3 above)
Comment (markbates) [inline generators/resource/templates/actions/resource-use_model.go.tmpl]: I think this should be a `302`.

File: generators/resource/templates/actions/resource-use_model.go.tmpl [hunk 5]
```diff
@@ -0,0 +1,172 @@
...
+	return c.Redirect(301, "/{{.underPlural}}")
```
Comment (markbates) [inline generators/resource/templates/actions/resource-use_model.go.tmpl]: I think this should be a `302`.

File: buffalo/cmd/generate/resource.go [hunk 6]
```diff
@@ -31,14 +31,23 @@ $ buffalo g resource users --skip-model
...
-//SkipResourceMigration allows to generate a resource without the migration.
+// SkipResourceMigration allows to generate a resource without the migration.
 var SkipResourceMigration = false
 
-//SkipResourceModel allows to generate a resource without the model and Migration.
+// SkipResourceModel allows to generate a resource without the model and Migration.
 var SkipResourceModel = false
 
+// UseResourceModel allows to generate a resource with a working model.
+var UseResourceModel = false
```
Comment (markbates) [inline buffalo/cmd/generate/resource.go]: this should be a `string` containing the name of the model to use.

```
buffalo g resource users --use-model=user
```

**Comment by markbates** [comment]
Some issues with pluralization:

```
buffalo g resource user name email
```

```
--> actions/user.go
--> actions/user_test.go
--> templates/users/_form.html
--> templates/users/edit.html
--> templates/users/index.html
--> templates/users/new.html
--> templates/users/show.html
--> buffalo db g model user name email
v3.13.5

--> models/user.go
--> models/user_test.go
--> goimports -w .
> migrations/20170329204449_create_users.up.fizz
> migrations/20170329204449_create_users.down.fizz
--> goimports -w .
```

In `actions/app.go`:

```go
var userResource buffalo.Resource
userResource = UserResource{&buffalo.BaseResource{}}
app.Resource("/user", userResource)
```

But the resource is named `UsersResource`.

**Comment by markbates** [comment]
It looks like the happy path is working great!

```
$ buffalo g resource users field1 field2 ...
$ buffalo g resource --skip-model users
```

These still have issues:

```
$ buffalo g resource user field1 field2 ...
$ buffalo g resource --use-model users
```

**Comment by as27** [comment]
* Changed template according to the review
* Minor changes to support different values for resource and model: `buffalo g r users --use-model people`
* Supports longer camel case names for example: UserComments

**Comment by as27** [comment]
Basic set of html templates are now generated.
It supports list, show, edit, new and delete out of the box.

**Comment by markbates** [comment]
https://github.com/gobuffalo/buffalo/pull/352

I fixed a few bugs and cleaned up some of the HTML.
