### PR TITLE
v0.16.27

### LINKED ISSUE #2117: buffalo dev: Package imported from implicitly required module
### Description

Running `buffalo dev` on a fresh project generated with `buffalo new` results in the following error:

```bash
buffalo: 2021/06/18 17:11:44 === Error! ===
buffalo: 2021/06/18 17:11:44 === exit status 1
go: btest2/actions: package github.com/gobuffalo/envy imported from implicitly required module; to add missing requirements, run:
	go get github.com/gobuffalo/envy@v1.9.0
go: btest2/actions: package github.com/gobuffalo/packr/v2 imported from implicitly required module; to add missing requirements, run:
	go get github.com/gobuffalo/packr/v2@v2.8.0
go: btest2/models: package github.com/gobuffalo/envy imported from implicitly required module; to add missing requirements, run:
	go get github.com/gobuffalo/envy@v1.9.0
go: btest2/models: package github.com/gobuffalo/pop/v5 imported from implicitly required module; to add missing requirements, run:
	go get github.com/gobuffalo/pop/v5@v5.3.0
 ===
```

### Steps to Reproduce the Problem

  1.  `buffalo new test`
  2.  `cd test`
  3.  `buffalo dev`
  4.   Error.

### Expected Behavior

I expected to have a running instance of the new app, as per https://gobuffalo.io/en/docs/getting-started/new-project/#running-your-application-in-development

### Actual Behavior

Dev server doesn't run, therefore there's nothing in the browser at http://localhost:3000

### Info

Please run `buffalo info` and paste the information below where it says "PASTE_HERE".

<details>

```
-> Go: Checking installation
✓ The `go` executable was found on your system at: /usr/local/bin/go

-> Go: Checking minimum version requirements
✓ Your version of Go, 1.14.15, meets the minimum requirements.

-> Go: Checking Package Management
✓ You are using Go Modules (`go`) for package management.

-> Go: Checking PATH
✓ Your PATH contains /Users/theothermatt/go/bin.

-> Node: Checking installation
✓ The `node` executable was found on your system at: /usr/local/bin/node

-> Node: Checking minimum version requirements
✓ Your version of Node, v14.17.1, meets the minimum requirements.

-> NPM: Checking installation
✓ The `npm` executable was found on your system at: /usr/local/bin/npm

-> NPM: Checking minimum version requirements
✓ Your version of NPM, 6.14.13, meets the minimum requirements.

-> Yarn: Checking installation
✓ The `yarnpkg` executable was found on your system at: /usr/local/bin/yarnpkg

-> Yarn: Checking minimum version requirements
✓ Your version of Yarn, 1.22.10, meets the minimum requirements.

-> PostgreSQL: Checking installation
✓ The `postgres` executable was found on your system at: /Applications/Postgres.app/Contents/Versions/latest/bin/postgres

-> PostgreSQL: Checking minimum version requirements
✓ Your version of PostgreSQL, 13.3.0, meets the minimum requirements.

-> MySQL: Checking installation
✘ The `mysql` executable could not be found on your system.
For help setting up your MySQL environment please follow the instructions for you platform at:

https://www.mysql.com/downloads/

-> SQLite3: Checking installation
✓ The `sqlite3` executable was found on your system at: /usr/bin/sqlite3

-> SQLite3: Checking minimum version requirements
✓ Your version of SQLite3, 3.28.0, meets the minimum requirements.

-> Cockroach: Checking installation
✘ The `cockroach` executable could not be found on your system.
For help setting up your Cockroach environment please follow the instructions for you platform at:

https://www.cockroachlabs.com/docs/stable/

-> Buffalo (CLI): Checking installation
✓ The `buffalo` executable was found on your system at: /usr/local/bin/buffalo

-> Buffalo (CLI): Checking minimum version requirements
✓ Your version of Buffalo (CLI), v0.16.23, meets the minimum requirements.

-> Buffalo: Application Details
Pwd         /Users/theothermatt/code/bctu/btest2
Root        /Users/theothermatt/code/bctu/btest2
GoPath      /Users/theothermatt/go
PackagePkg  btest2
ActionsPkg  btest2/actions
ModelsPkg   btest2/models
GriftsPkg   btest2/grifts
WithModules true
Name        btest2
Bin         bin/btest2
VCS         git
WithPop     true
WithSQLite  false
WithDep     false
WithWebpack true
WithNodeJs  true
WithYarn    true
WithDocker  true
WithGrifts  true
AsWeb       true
AsAPI       false
InApp       true
PackageJSON {map[build:webpack -p --progress dev:webpack --watch]}

-> Buffalo: config/buffalo-app.toml
name = "btest2"
bin = "bin/btest2"
vcs = "git"
with_pop = true
with_sqlite = false
with_dep = false
with_webpack = true
with_nodejs = true
with_yarn = true
with_docker = true
with_grifts = true
as_web = true
as_api = false

-> Buffalo: config/buffalo-plugins.toml
[[plugin]]
  binary = "buffalo-pop"
  go_get = "github.com/gobuffalo/buffalo-pop/v2"

-> Buffalo: go.mod
module btest2

go 1.16

require github.com/gobuffalo/buffalo-pop/v2 v2.3.0 // indirect
```

</details>

### PR DESCRIPTION
**Pull request by paganotoni**
- Fixes #2117
- Adds stale issues automated handler

### CODE REVIEW

File: buffalo/cmd/new.go [hunk 1]
```diff
@@ -201,6 +201,12 @@ var newCmd = &cobra.Command{
 		}
 		run.WithGroup(gg)
 
+		g := genny.New()
+		g.Command(exec.Command("go", "mod", "tidy"))
```
Comment (bryanjhv) [inline buffalo/cmd/new.go:205]: I'm not sure if what I'm about to say goes here but:
After testing this PR on Codespaces (and locally), `go.mod` still contains old versions (Buffalo 0.15.5 instead of 0.16.27, etc.).
I mean, it solves the things one had to run manually after a `buffalo new`, but maybe after a new release it would be helpful to check out these versioning things.

PS: I'm guessing it's because of the `go get github.com/gobuffalo/buffalo-pop/v2` (which adds an indirect dependency, but the `2.3.0` version depends on an old Buffalo, or idk, don't know a lot about how Go handles dependencies).

Only thing that worked for me in order to use latest is:

```bash
rm go.*
go mod init [project]
go mod tidy
```

**Comment by rahiyansafz** [comment]
BUFFALO IS THE BEST THING THAT EVER HAPPENED TO ME!!!!!!!!

File: buffalo/cmd/new.go (hunk 1 above)
Comment (paganotoni) [reply buffalo/cmd/new.go:205]: Good point @bryanjhv. I think we need to make sure that works before merging this PR. Thanks for the heads up.

Comment (paganotoni) [reply buffalo/cmd/new.go:205]: While running `buffalo new app` I did find the following error:

# github.com/gobuffalo/buffalo-pop/v2
/usr/local/go/pkg/tool/darwin_arm64/link: /usr/local/go/pkg/tool/darwin_arm64/link: combining dwarf failed: unknown load command 0x80000034 (2147483700)

Comment (rahiyansafz) [reply buffalo/cmd/new.go:205]: same problem!

Comment (bryanjhv) [reply buffalo/cmd/new.go:205]: Which Go version are you using?
I tested it on Linux and everything went smooth.
Maybe it's specific to Mac OS? Maybe another regression?
https://github.com/golang/go/issues/25908

Comment (paganotoni) [reply buffalo/cmd/new.go:205]: Yes. Agree, this seems to be specific to apple M1 chips.

Comment (fasmat) [reply buffalo/cmd/new.go:205]: Concerning the topic of updating direct dependencies after creating a new application with `buffalo new`: I added this functionality in the following PR: https://github.com/gobuffalo/buffalo/pull/2128

Comment (paganotoni) [reply buffalo/cmd/new.go:206]: @fasmat Just merged it. I think this is related with #2130 as we will move the CLI out of the buffalo library. I think that would be best.
