### PR TITLE
fixes #183

### LINKED ISSUE #183: Silent failure of unknown db type
If you run the following.

`buffalo new coke --db-type SOMETHING-BAD! > result.out 2>&1`

It seems like the db setup fails silently due to the unknown type being passed. I don't see a warning in the output file.

The issue seems to be around here https://github.com/gobuffalo/buffalo/blob/master/buffalo/cmd/soda_generators.go#L34.

`generate.GenerateConfig("./database.yml", data)` returns an error but is being ignored and instead on line 35 nil is being returned silencing the error.

Possible solution is to return the error from GenerateConfig.

```go
g.Add(&gentronics.Func{
		Should: should,
		Runner: func(rootPath string, data gentronics.Data) error {
			data["dialect"] = data["dbType"]
			return generate.GenerateConfig("./database.yml", data)
		},
	})
```

This change results in the following output but does not fail the new app from generating. However, it does give the user some information to know what went wrong.

`Error: Could not initialize something-bad!!`

However, a better solution is to return the error but also validate the arguments being supplied by the user and bail out if they are invalid with a helpful message.

I can come up with a pull request for this if this sounds good.

### PR DESCRIPTION
**Pull request by amedeiros**
Fixes the silent failing of a unknown db-type. The following is the result.

```
buffalo new coke --db-type SOMETHING-BAD!

Buffalo version 0.7.1

Error: Unknown db-type SOMETHING-BAD! expecting one of postgres, mysql or sqlite3
Usage:
  buffalo new [name] [flags]

Flags:
      --db-type string   specify the type of database you want to use [postgres, mysql, sqlite3] (default "postgres")
  -f, --force            delete and remake if the app already exists
      --skip-pop         skips adding pop/soda to your app
      --skip-webpack     skips adding Webpack to your app
  -v, --verbose          verbosely print out the go get/install commands
```

### CODE REVIEW

File: buffalo/cmd/root.go [hunk 1]
```diff
@@ -44,7 +44,6 @@ var RootCmd = &cobra.Command{
 // This is called by main.main(). It only needs to happen once to the rootCmd.
 func Execute() {
 	if err := RootCmd.Execute(); err != nil {
-		fmt.Println(err)
```
Comment (markbates) [inline buffalo/cmd/root.go]: why did you remove the printing of the error here? or was that a mistake?

Comment (amedeiros) [inline buffalo/cmd/root.go]: I removed it because it was causing the error to be printed twice.

Comment (amedeiros) [inline buffalo/cmd/root.go]: Instead of the following

```
buffalo new coke --db-type SOMETHING-BAD!
Buffalo version 0.7.1

Error: Unknown db-type SOMETHING-BAD! expecting one of postgres, mysql or sqlite3
Usage:
  buffalo new [name] [flags]

Flags:
      --db-type string   specify the type of database you want to use [postgres, mysql, sqlite3] (default "postgres")
  -f, --force            delete and remake if the app already exists
      --skip-pop         skips adding pop/soda to your app
      --skip-webpack     skips adding Webpack to your app
  -v, --verbose          verbosely print out the go get/install commands```

You would get the error out put again at the end. Shown below.

```
buffalo new coke --db-type SOMETHING-BAD!
Buffalo version 0.7.1

Error: Unknown db-type SOMETHING-BAD! expecting one of postgres, mysql or sqlite3
Usage:
  buffalo new [name] [flags]

Flags:
      --db-type string   specify the type of database you want to use [postgres, mysql, sqlite3] (default "postgres")
  -f, --force            delete and remake if the app already exists
      --skip-pop         skips adding pop/soda to your app
      --skip-webpack     skips adding Webpack to your app
  -v, --verbose          verbosely print out the go get/install commands

Unknown db-type SOMETHING-BAD! expecting one of postgres, mysql or sqlite3```

**Comment by markbates** [comment]
looks good. thanks!

**Comment by amedeiros** [comment]
@markbates Thanks for the merge. I was just messing with error message situation. If setting the root command to silence errors we can add that println back and it will instead print the error at the end. I guess its a trade off on where the message gets printed really.

```go
// RootCmd is the hook for all of the other commands in the buffalo binary.
var RootCmd = &cobra.Command{
	SilenceErrors: true,
	Use:   "buffalo",
	Short: "Helps you build your Buffalo applications that much easier!",
	PersistentPreRun: func(cmd *cobra.Command, args []string) {
		fmt.Printf("Buffalo version %s\n\n", Version)
	},
}

// Execute adds all child commands to the root command sets flags appropriately.
// This is called by main.main(). It only needs to happen once to the rootCmd.
func Execute() {
	if err := RootCmd.Execute(); err != nil {
		fmt.Println(fmt.Sprintf("Error: %s", err))
		os.Exit(-1)
	}
}
```

That will result in the following output instead.

```
buffalo new coke --db-type SOMETHING-BAD!
Buffalo version 0.7.1

Usage:
  buffalo new [name] [flags]

Flags:
      --db-type string   specify the type of database you want to use [postgres, mysql, sqlite3] (default "postgres")
  -f, --force            delete and remake if the app already exists
      --skip-pop         skips adding pop/soda to your app
      --skip-webpack     skips adding Webpack to your app
  -v, --verbose          verbosely print out the go get/install commands

Error: Unknown db-type SOMETHING-BAD! expecting one of postgres, mysql or sqlite3
```
