### PR TITLE
Fixes #1987 and #2023

### LINKED ISSUE #1987: Missing i18n import with --api flag
### Description
Using the latest 0.16.8 generating an api with --api result in a project that cannot be compiled once you add a resource to the project

### Steps to Reproduce the Problem

  1. buffalo new coke --api
  2. buffalo g resource profile name
  3. buffalo dev

result:
generatedApps/seizetst02/models
generatedApps/seizetst02/actions
#generatedApps/seizetst02/actions
actions/profiles.go:133:30: undefined: T
actions/profiles.go:189:30: undefined: T
actions/profiles.go:223:30: undefined: T
buffalo: 2020/05/04 10:14:25 === Error! ===
buffalo: 2020/05/04 10:14:25 === exit status 2

###  Solution
In app.go add the following missing line:
import i18n "github.com/gobuffalo/mw-i18n"
var T *i18n.Translator //missing

Note: thosse lines are generated in regular Html app (non --api)

### PR DESCRIPTION
**Pull request by paganotoni**
- Adds i18n middleware to the api generated apps.
- Fixes names of the actions in the resource generated with --skip-model

### CODE REVIEW

File: genny/resource/templates/standard/actions/resource-name.go.tmpl [hunk 1]
```diff
@@ -11,8 +11,8 @@ type {{.opts.Name.Resource}}Resource struct{
 }
 
 {{ range $a := .actions }}
-// {{$a.String}} default implementation.
-func (v {{$.opts.Name.Resource}}Resource) {{$a.String}}(c buffalo.Context) error {
+// {{$a.Pascalize}} default implementation.
+func (v {{$.opts.Name.Resource}}Resource) {{$a.Pascalize}}(c buffalo.Context) error {
   return c.Render(http.StatusOK, r.String("{{$.opts.Model.Proper}}#{{$a.String}}"))
```
Comment (PeterdeJ) [inline genny/resource/templates/standard/actions/resource-name.go.tmpl:16]: Don't forget about the "$a.String" in this one:) I believe this should also be "$a.Pascalize"?

Comment (paganotoni) [reply genny/resource/templates/standard/actions/resource-name.go.tmpl]: Covered. Thanks!
